package com.tsuyu.line;

import android.Manifest;
import android.content.pm.PackageManager;
import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;

public final class Ui {
    public static final int BG=0xff0d0b12,CARD=0xff1c1724,SURFACE=0xff15111c,PURPLE=0xffc8a7ff,TEXT=0xfff7f0ff,MUTED=0xffa99bb8,LINE=0xff352a43;
    public static final int WHITE=0xffffffff,ZINC=0xffd4d4d8,ZINC4=0xffa1a1aa,ZINC6=0xff52525b,AMBER=0xffffcf70,EMERALD=0xff88e0a0,NAV=0xff15111c;
    private static Typeface cachedFont;private static long cachedFontAt;
    public interface Choice {void pick(int index);}
    public interface MultiChoice {void pick(boolean[] checked);}
    public static int dp(Context c,int n){return Math.round(n*c.getResources().getDisplayMetrics().density);}
    public static Drawable shape(int color,int r,Context c){GradientDrawable d=new GradientDrawable();d.setCornerRadius(dp(c,r));d.setColor(color);return d;}
    public static Drawable gradient(int start,int end,int r,Context c){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{start,end});d.setCornerRadius(dp(c,r));return d;}
    public static Drawable stroke(int bg,int r,Context c){GradientDrawable d=new GradientDrawable();d.setColor(bg);d.setCornerRadius(dp(c,r));d.setStroke(dp(c,1),LINE);return d;}
    public static Drawable stroke(int bg,int r,int strokeColor,Context c){GradientDrawable d=new GradientDrawable();d.setColor(bg);d.setCornerRadius(dp(c,r));d.setStroke(dp(c,1),strokeColor);return d;}
    public static LinearLayout column(Context c){LinearLayout v=new LinearLayout(c);v.setOrientation(LinearLayout.VERTICAL);return v;}
    public static LinearLayout row(Context c){LinearLayout v=new LinearLayout(c);v.setOrientation(LinearLayout.HORIZONTAL);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    public static LinearLayout.LayoutParams lp(Context c,int width,int height){return new LinearLayout.LayoutParams(width<0?width:dp(c,width),height<0?height:dp(c,height));}
    public static void space(LinearLayout v,int height){View a=new View(v.getContext());v.addView(a,lp(v.getContext(),1,height));}
    public static void press(View v){v.setClickable(true);v.setFocusable(true);v.setOnTouchListener((view,e)->{if(!view.isEnabled())return false;if(YoruApp.app()!=null&&YoruApp.app().store!=null&&YoruApp.app().store.ready()&&YoruApp.app().store.liteMode())return false;if(e.getAction()==android.view.MotionEvent.ACTION_DOWN)view.animate().scaleX(.965f).scaleY(.965f).alpha(.86f).setDuration(45).start();else if(e.getAction()==android.view.MotionEvent.ACTION_UP||e.getAction()==android.view.MotionEvent.ACTION_CANCEL)view.animate().scaleX(1f).scaleY(1f).alpha(1f).setDuration(60).start();return false;});}
    public static TextView button(Context c,String title,boolean primary,Runnable action){TextView t=text(c,title,14,primary?0xff21152f:TEXT,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(c,18),dp(c,13),dp(c,18),dp(c,13));t.setMinHeight(dp(c,48));t.setBackground(primary?gradient(0xffe2ccff,PURPLE,16,c):stroke(CARD,16,c));press(t);t.setOnClickListener(v->{if(action!=null)action.run();});return t;}
    public static TextView chip(Context c,String title,boolean selected,Runnable action){TextView t=text(c,title,12,selected?0xff21152f:MUTED,true);t.setSingleLine();t.setEllipsize(android.text.TextUtils.TruncateAt.END);t.setPadding(dp(c,14),dp(c,10),dp(c,14),dp(c,10));t.setBackground(selected?gradient(0xffe2ccff,PURPLE,13,c):stroke(SURFACE,13,c));press(t);t.setOnClickListener(v->{if(action!=null)action.run();});return t;}
    public static View iconButton(Context c,String name,String desc,Runnable action){Icon i=new Icon(c,name);i.setContentDescription(desc);i.setBackground(stroke(SURFACE,15,c));press(i);i.setOnClickListener(v->{if(action!=null)action.run();});return i;}
    public static void gap(LinearLayout row,View child,int width,int height,int left){LinearLayout.LayoutParams p=lp(row.getContext(),width,height);p.leftMargin=dp(row.getContext(),left);row.addView(child,p);}
    public static void toast(Context c,String s){Toast toast=new Toast(c.getApplicationContext());TextView t=text(c,s,12,TEXT,true);t.setPadding(dp(c,16),dp(c,12),dp(c,16),dp(c,12));t.setBackground(stroke(0xf021192d,18,c));toast.setView(t);toast.setDuration(Toast.LENGTH_SHORT);toast.setGravity(Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL,0,dp(c,76));toast.show();}
    public static LinearLayout base(Activity a){a.getWindow().setStatusBarColor(BG);a.getWindow().setNavigationBarColor(BG);a.getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);LinearLayout root=column(a);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});a.setContentView(root);root.requestApplyInsets();root.setAlpha(1f);if(Build.VERSION.SDK_INT>=33)a.getOnBackInvokedDispatcher().registerOnBackInvokedCallback(0,a::onBackPressed);return root;}
    public static boolean allow(Activity a){return true;}
    public static void openDetails(Context c,Anime a){c.startActivity(new Intent(c,DetailsActivity.class).putExtra("anime",a.json().toString()));}
    public static void openImage(Context c,String url,String title){c.startActivity(new Intent(c,ImageViewerActivity.class).putExtra("url",url).putExtra("title",title));}
    public static void openPlayer(Context c,Anime a,String mode,double episode){openPlayer(c,a,mode,episode,-1,"");}
    public static void openPlayer(Context c,Anime a,String mode,double episode,long seekMs){openPlayer(c,a,mode,episode,seekMs,"");}
    public static void openPlayer(Context c,Anime a,String mode,double episode,long seekMs,String preferredVoice){if(mode==null||mode.equals("auto")||mode.equals("offline")){androidx.media3.exoplayer.offline.Download d=YoruApp.app().downloads().findCompleted(a,episode);if(d!=null){openOffline(c,d.request.id,a,episode);return;}}Intent i=new Intent(c,PlayerActivity.class).putExtra("anime",a.json().toString()).putExtra("mode",mode).putExtra("episode",episode);if(seekMs>=0)i.putExtra("seekMs",seekMs);if(preferredVoice!=null&&!preferredVoice.isEmpty())i.putExtra("dubbing",preferredVoice);c.startActivity(i);}
    public static Anime intentAnime(Activity a){try{return Anime.from(new JSONObject(a.getIntent().getStringExtra("anime")));}catch(Exception e){return new Anime();}}
    public static String time(int sec){sec=Math.max(0,sec);return String.format(Locale.ROOT,"%d:%02d",sec/60,sec%60);}
    public static Dialog custom(Activity a,String title,View content,String positive,Runnable onPositive,String neutral,Runnable onNeutral,String negative){Dialog d=new Dialog(a);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout box=column(a);box.setPadding(dp(a,18),dp(a,18),dp(a,18),dp(a,16));box.setBackground(stroke(0xff1f1829,24,a));TextView head=text(a,title,20,TEXT,true);box.addView(head);if(content!=null){space(box,14);ViewGroup.LayoutParams cp=content.getLayoutParams();if(cp instanceof LinearLayout.LayoutParams)box.addView(content,(LinearLayout.LayoutParams)cp);else box.addView(content,new LinearLayout.LayoutParams(-1,-2));}space(box,16);LinearLayout actions=row(a);actions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);if(negative!=null&&!negative.isEmpty()){TextView b=button(a,negative,false,()->d.dismiss());actions.addView(b,new LinearLayout.LayoutParams(0,-2,1));}if(neutral!=null&&!neutral.isEmpty()){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.leftMargin=dp(a,8);TextView b=button(a,neutral,false,()->{d.dismiss();if(onNeutral!=null)onNeutral.run();});actions.addView(b,p);}if(positive!=null&&!positive.isEmpty()){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.leftMargin=dp(a,8);TextView b=button(a,positive,true,()->{d.dismiss();if(onPositive!=null)onPositive.run();});actions.addView(b,p);}box.addView(actions);d.setContentView(box);d.setOnShowListener(x->{Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));WindowManager.LayoutParams p=w.getAttributes();p.dimAmount=.64f;w.setAttributes(p);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);int width=a.getResources().getDisplayMetrics().widthPixels-dp(a,30);w.setLayout(Math.min(width,dp(a,560)),WindowManager.LayoutParams.WRAP_CONTENT);}});d.show();return d;}
    public static Dialog customX(Activity a,String title,View content,String positive,Runnable onPositive,String neutral,Runnable onNeutral){Dialog d=new Dialog(a);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout box=column(a);box.setPadding(dp(a,18),dp(a,18),dp(a,18),dp(a,16));box.setBackground(stroke(0xff1f1829,24,a));LinearLayout head=row(a);head.addView(text(a,title,20,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));Icon x=new Icon(a,"close");x.color=TEXT;x.setPadding(dp(a,9),dp(a,9),dp(a,9),dp(a,9));press(x);x.setOnClickListener(v->d.dismiss());head.addView(x,lp(a,40,40));box.addView(head);if(content!=null){space(box,14);ViewGroup.LayoutParams cp=content.getLayoutParams();if(cp instanceof LinearLayout.LayoutParams)box.addView(content,(LinearLayout.LayoutParams)cp);else box.addView(content,new LinearLayout.LayoutParams(-1,-2));}space(box,16);LinearLayout actions=row(a);actions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);if(neutral!=null&&!neutral.isEmpty()){TextView b=button(a,neutral,false,()->{d.dismiss();if(onNeutral!=null)onNeutral.run();});actions.addView(b,new LinearLayout.LayoutParams(0,-2,1));}if(positive!=null&&!positive.isEmpty()){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.leftMargin=dp(a,8);TextView b=button(a,positive,true,()->{d.dismiss();if(onPositive!=null)onPositive.run();});actions.addView(b,p);}box.addView(actions);d.setContentView(box);d.setOnShowListener(ev->{Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));WindowManager.LayoutParams p=w.getAttributes();p.dimAmount=.64f;w.setAttributes(p);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);int width=a.getResources().getDisplayMetrics().widthPixels-dp(a,30);w.setLayout(Math.min(width,dp(a,560)),WindowManager.LayoutParams.WRAP_CONTENT);}});d.show();return d;}
    public static void singleChoice(Activity a,String title,String[] options,int current,String positive,Choice onPick){int[] chosen=new int[]{current};LinearLayout box=column(a);RadioGroup group=new RadioGroup(a);for(int i=0;i<options.length;i++){RadioButton b=new RadioButton(a);b.setText(options[i]);b.setTextColor(TEXT);b.setTextSize(13);b.setTypeface(typeface(a,false));b.setId(i+1);b.setPadding(dp(a,6),dp(a,10),dp(a,6),dp(a,10));if(Build.VERSION.SDK_INT>=21)b.setButtonTintList(android.content.res.ColorStateList.valueOf(PURPLE));group.addView(b);if(i==current)b.setChecked(true);}group.setOnCheckedChangeListener((g,id)->chosen[0]=id-1);ScrollView scroll=new ScrollView(a);scroll.addView(group);box.addView(scroll,lp(a,-1,Math.min(320,options.length*44+10)));custom(a,title,box,positive,()->{if(onPick!=null&&chosen[0]>=0)onPick.pick(chosen[0]);},null,null,"Отмена");}
    public static void multiChoice(Activity a,String title,String[] options,boolean[] checked,String positive,MultiChoice onPick){boolean[] state=Arrays.copyOf(checked,checked.length);LinearLayout box=column(a);ScrollView scroll=new ScrollView(a);LinearLayout list=column(a);for(int i=0;i<options.length;i++){final int index=i;CheckBox b=new CheckBox(a);b.setText(options[i]);b.setTextColor(TEXT);b.setTextSize(13);b.setTypeface(typeface(a,false));b.setChecked(state[i]);b.setPadding(dp(a,6),dp(a,10),dp(a,6),dp(a,10));if(Build.VERSION.SDK_INT>=21)b.setButtonTintList(android.content.res.ColorStateList.valueOf(PURPLE));b.setOnCheckedChangeListener((btn,v)->state[index]=v);list.addView(b);}scroll.addView(list);box.addView(scroll,lp(a,-1,Math.min(320,options.length*44+10)));custom(a,title,box,positive,()->{if(onPick!=null)onPick.pick(state);},null,null,"Отмена");}
    public static TextView label(Context c,String s){TextView t=text(c,s,10,MUTED,true);t.setLetterSpacing(.08f);return t;}
    public static Dialog message(Activity a,String title,String message){return message(a,title,message,"Понятно",null);}
    public static Dialog message(Activity a,String title,String message,String ok,Runnable done){TextView body=text(a,message,13,MUTED,false);body.setLineSpacing(dp(a,4),1);return custom(a,title,body,ok,done,null,null,null);}
    public static Dialog choices(Activity a,String title,String[] items,Choice choice){ListView list=new ListView(a);list.setDivider(null);list.setCacheColorHint(Color.TRANSPARENT);list.setVerticalScrollBarEnabled(false);list.setBackgroundColor(Color.TRANSPARENT);list.setAdapter(new TextListAdapter(a,items,null,null));list.setOnItemClickListener((p,v,pos,id)->{Dialog d=(Dialog)list.getTag();if(d!=null)d.dismiss();if(choice!=null)choice.pick(pos);});list.setLayoutParams(new LinearLayout.LayoutParams(-1,Math.min(dp(a,430),dp(a,54*Math.max(1,Math.min(items.length,8))))));Dialog d=custom(a,title,list,null,null,null,null,"Закрыть");list.setTag(d);return d;}
    private static final class TextListAdapter extends BaseAdapter {private final Context c;private final String[] items;private final int[] selected;private final boolean[] checked;TextListAdapter(Context c,String[] i,int[] s,boolean[] m){this.c=c;items=i==null?new String[0]:i;selected=s;checked=m;}public int getCount(){return items.length;}public Object getItem(int p){return items[p];}public long getItemId(int p){return p;}public View getView(int p,View old,ViewGroup parent){LinearLayout row=row(c);row.setPadding(dp(c,12),dp(c,8),dp(c,12),dp(c,8));boolean on=selected!=null&&selected[0]==p||checked!=null&&checked[p];row.setBackground(on?shape(0x14FFFFFF,14,c):shape(0x00000000,14,c));TextView mark=text(c,on?"✓":"",16,PURPLE,true);mark.setGravity(Gravity.CENTER);row.addView(mark,lp(c,28,38));TextView label=text(c,items[p],13,on?TEXT:MUTED,true);label.setMaxLines(3);label.setEllipsize(android.text.TextUtils.TruncateAt.END);row.addView(label,new LinearLayout.LayoutParams(0,-2,1));return row;}}
    public static void confirm(Activity a,String title,String message,String positive,Runnable onPositive,String negative){LinearLayout box=column(a);TextView text=text(a,message,13,MUTED,false);text.setLineSpacing(dp(a,4),1);box.addView(text);custom(a,title,box,positive,onPositive,null,null,negative);}
    public static final class Progress {private final Dialog dialog;private final TextView status;Progress(Dialog d,TextView s){dialog=d;status=s;}public void update(String text){if(status!=null)status.setText(text);}public void setMessage(String s){if(status!=null)status.setText(s);}public void dismiss(){try{if(dialog!=null&&dialog.isShowing())dialog.dismiss();}catch(Exception ignored){}}public boolean isShowing(){return dialog!=null&&dialog.isShowing();}}
    public static Progress progress(Activity a,String message,boolean cancelable,Runnable onCancel){Dialog d=new Dialog(a);d.requestWindowFeature(Window.FEATURE_NO_TITLE);d.setCancelable(cancelable);LinearLayout box=column(a);box.setPadding(dp(a,22),dp(a,22),dp(a,22),dp(a,20));box.setBackground(stroke(0xff1f1829,24,a));box.setGravity(Gravity.CENTER_HORIZONTAL);ProgressBar bar=new ProgressBar(a);if(Build.VERSION.SDK_INT>=21)bar.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(PURPLE));box.addView(bar);space(box,14);TextView msg=text(a,message,13,TEXT,true);msg.setGravity(Gravity.CENTER);msg.setLineSpacing(dp(a,4),1);box.addView(msg);if(cancelable){space(box,14);TextView b=button(a,"Отмена",false,()->{d.dismiss();if(onCancel!=null)onCancel.run();});box.addView(b,new LinearLayout.LayoutParams(-1,-2));}d.setContentView(box);d.setOnShowListener(x->{Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));WindowManager.LayoutParams p=w.getAttributes();p.dimAmount=.64f;w.setAttributes(p);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);int width=a.getResources().getDisplayMetrics().widthPixels-dp(a,40);w.setLayout(Math.min(width,dp(a,380)),WindowManager.LayoutParams.WRAP_CONTENT);}});d.show();return new Progress(d,msg);}
    public static String number(double n){return n==Math.floor(n)?String.valueOf((int)Math.floor(n)):String.valueOf(n);}
    public static void bucketDialog(Activity a,Anime anime,Runnable done){SecureStore store=YoruApp.app().store;String current="";try{current=store.bucket(anime);}catch(Exception ignored){}final String activeBucket=current;LinearLayout col=column(a);col.setPadding(dp(a,2),0,dp(a,2),0);TextView hint=text(a,YoruBrain.title(anime),13,MUTED,false);hint.setMaxLines(2);hint.setEllipsize(android.text.TextUtils.TruncateAt.END);col.addView(hint);space(col,12);final Dialog[] box=new Dialog[1];String[] buckets=SecureStore.BUCKETS,labels=SecureStore.BUCKET_LABELS;for(int i=0;i<buckets.length&&i<labels.length;i++){final String bucket=buckets[i],label=labels[i];TextView button=button(a,(bucket.equals(activeBucket)?"✓ ":"")+label,bucket.equals(activeBucket),null);button.setOnClickListener(v->{if(box[0]!=null)box[0].dismiss();saveBucket(a,anime,bucket,label,done);});col.addView(button,lp(a,-1,-2));space(col,8);}TextView folders=button(a,"Папки / полки",false,null);folders.setOnClickListener(v->{if(box[0]!=null)box[0].dismiss();folderDialog(a,anime,done);});col.addView(folders,lp(a,-1,-2));if(!activeBucket.isEmpty()){space(col,8);TextView remove=button(a,"Убрать из коллекции",false,null);remove.setOnClickListener(v->{if(box[0]!=null)box[0].dismiss();saveBucket(a,anime,"","",done);});col.addView(remove,lp(a,-1,-2));}box[0]=custom(a,"Моя коллекция",col,null,null,null,null,"Закрыть");}
    private static void saveBucket(Activity a,Anime anime,String bucket,String label,Runnable done){YoruApp.app().store.favorite(anime,bucket);if(!bucket.isEmpty()){if(Build.VERSION.SDK_INT>=33&&a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},4201);EpisodeUpdateReceiver.checkNow(a);toast(a,"Добавлено в “"+label+"”");}else toast(a,"Удалено из коллекции");if(done!=null)done.run();}
    public static void folderDialog(Activity a,Anime anime,Runnable done){SecureStore store=YoruApp.app().store;ArrayList<String> folders=store.libraryFolders();ArrayList<String> current=store.folders(anime);LinearLayout col=column(a);col.setPadding(dp(a,2),0,dp(a,2),0);TextView hint=text(a,"Папки не заменяют статусы коллекции Один тайтл может быть в “Смотрю” и одновременно на полках “С друзьями”, “4K”, “Пересмотреть”",11,MUTED,false);hint.setLineSpacing(dp(a,4),1);col.addView(hint);space(col,12);ArrayList<CheckBox> checks=new ArrayList<>();if(!folders.isEmpty()){ScrollView sc=new ScrollView(a);LinearLayout list=column(a);for(String f:folders){CheckBox cb=new CheckBox(a);cb.setText(f);cb.setTextColor(TEXT);cb.setTextSize(13);cb.setTypeface(typeface(a,false));cb.setChecked(current.contains(f));list.addView(cb,lp(a,-1,46));checks.add(cb);}sc.addView(list);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Math.min(dp(a,260),dp(a,46*Math.max(1,folders.size())))));col.addView(sc);}else col.addView(text(a,"Пока нет созданных папок — задайте первую ниже",12,MUTED,false));space(col,10);EditText input=new EditText(a);input.setSingleLine(false);input.setMinLines(1);input.setMaxLines(2);input.setTextColor(TEXT);input.setHintTextColor(MUTED);input.setHint("Новая папка или несколько через запятую");input.setTextSize(13);input.setTypeface(typeface(a,false));input.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(96)});input.setBackground(stroke(SURFACE,13,a));input.setPadding(dp(a,12),0,dp(a,12),0);col.addView(input,lp(a,-1,52));Dialog dialog=custom(a,"Папки",col,"ОК",()->{ArrayList<String> selected=new ArrayList<>();for(CheckBox cb:checks)if(cb.isChecked())selected.add(cb.getText().toString());String extra=input.getText()==null?"":input.getText().toString();for(String part:extra.split(",")){String v=part.trim();if(!v.isEmpty())selected.add(v);}store.favoriteFolders(anime,selected);if(Build.VERSION.SDK_INT>=33&&a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},4201);EpisodeUpdateReceiver.checkNow(a);toast(a,selected.isEmpty()?"Папки очищены":"Папки обновлены");if(done!=null)done.run();},current.isEmpty()?null:"Очистить",()->{store.favoriteFolders(anime,new ArrayList<>());toast(a,"Папки очищены");if(done!=null)done.run();},"Отмена");}
    public static Typeface typeface(Context c,boolean bold){long now=System.currentTimeMillis();if(cachedFont!=null&&now-cachedFontAt<10_000L)return cachedFont;Typeface custom=loadCustomFont(c);if(custom!=null){cachedFont=custom;cachedFontAt=now;return custom;}cachedFont=bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT;cachedFontAt=now;return cachedFont;}
    public static void clearFontCache(){cachedFont=null;cachedFontAt=0;}
    private static Typeface loadCustomFont(Context c){try{if(YoruApp.app()==null||YoruApp.app().store==null||!YoruApp.app().store.ready()||!YoruApp.app().store.customFont())return null;File file=new File(c.getFilesDir(),"yoru_custom_font.ttf");if(!file.exists()||file.length()<1024)return null;return Typeface.createFromFile(file);}catch(Exception ignored){return null;}}
    public static TextView text(Context c,String text,int sp,int color,boolean bold){TextView t=new TextView(c);t.setText(text);t.setTextColor(color);int scale=YoruApp.app()!=null&&YoruApp.app().store!=null&&YoruApp.app().store.ready()?YoruApp.app().store.fontScale():100;float scaled=Math.max(10f,sp*(scale/100f));t.setTextSize(scaled);t.setTypeface(typeface(c,bold));return t;}
    public static View cardSetting(Context c,String title,String desc,String value,Runnable click){LinearLayout row=row(c);row.setPadding(dp(c,16),dp(c,14),dp(c,16),dp(c,14));row.setBackground(stroke(CARD,18,c));press(row);row.setOnClickListener(v->{if(click!=null)click.run();});LinearLayout text=column(c);text.addView(text(c,title,14,TEXT,true));if(desc!=null&&!desc.isEmpty()){space(text,4);text.addView(text(c,desc,11,MUTED,false));}row.addView(text,new LinearLayout.LayoutParams(0,-2,1));if(value!=null&&!value.isEmpty()){TextView val=text(c,value,12,PURPLE,true);val.setPadding(dp(c,10),dp(c,6),dp(c,10),dp(c,6));val.setBackground(stroke(SURFACE,11,c));row.addView(val);}return row;}
    public static View chipRow(Context c,String label,String value,Runnable click){LinearLayout row=row(c);row.setPadding(dp(c,14),dp(c,10),dp(c,14),dp(c,10));row.setBackground(stroke(SURFACE,14,c));press(row);row.setOnClickListener(v->{if(click!=null)click.run();});row.addView(text(c,label,12,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));row.addView(text(c,value,12,PURPLE,true));return row;}
    public static View simpleSwitch(Context c,String title,String desc,boolean checked,CompoundButton.OnCheckedChangeListener change){LinearLayout row=row(c);row.setPadding(dp(c,16),dp(c,14),dp(c,16),dp(c,14));row.setBackground(stroke(CARD,18,c));LinearLayout text=column(c);text.addView(text(c,title,14,TEXT,true));if(desc!=null&&!desc.isEmpty()){space(text,4);text.addView(text(c,desc,11,MUTED,false));}row.addView(text,new LinearLayout.LayoutParams(0,-2,1));Switch sw=new Switch(c);sw.setChecked(checked);sw.setOnCheckedChangeListener(change);row.addView(sw);return row;}
    public static View folderRow(Context c,String name,int count,Runnable open,Runnable delete){LinearLayout row=row(c);row.setPadding(dp(c,16),dp(c,14),dp(c,14),dp(c,14));row.setBackground(stroke(CARD,18,c));press(row);row.setOnClickListener(v->{if(open!=null)open.run();});Icon i=new Icon(c,"bookmark");i.color=PURPLE;row.addView(i,lp(c,20,20));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.leftMargin=dp(c,12);LinearLayout info=column(c);info.addView(text(c,name,14,TEXT,true));space(info,3);info.addView(text(c,count+" аниме",11,MUTED,false));row.addView(info,tp);Icon del=new Icon(c,"trash");del.color=0xffff8f9f;del.setPadding(dp(c,8),dp(c,8),dp(c,8),dp(c,8));press(del);del.setOnClickListener(v->{if(delete!=null)delete.run();});row.addView(del,lp(c,38,38));return row;}
    public static View historyRow(Context c,Anime a,JSONObject h,Runnable open,Runnable remove){LinearLayout row=row(c);row.setPadding(dp(c,14),dp(c,11),dp(c,14),dp(c,11));row.setBackground(stroke(CARD,16,c));press(row);row.setOnClickListener(v->{if(open!=null)open.run();});ImageView poster=new ImageView(c);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setBackground(shape(SURFACE,11,c));poster.setClipToOutline(true);YoruApp.app().images.load(poster,a);row.addView(poster,lp(c,48,68));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.leftMargin=dp(c,12);LinearLayout text=column(c);text.addView(text(c,YoruBrain.title(a),13,TEXT,true));space(text,4);int time=h.optInt("time"),duration=h.optInt("duration");double ep=h.optDouble("episode",1);String dub=h.optString("dubbing","");if(!dub.isEmpty())dub=" · "+ApiRepository.voiceTitle(dub);text.addView(text(c,"Серия "+number(ep)+" · "+time(time)+(duration>0?" / "+time(duration):"")+dub,11,MUTED,false));row.addView(text,tp);Icon del=new Icon(c,"close");del.color=MUTED;del.setPadding(dp(c,9),dp(c,9),dp(c,9),dp(c,9));press(del);del.setOnClickListener(v->{if(remove!=null)remove.run();});row.addView(del,lp(c,38,38));return row;}
    public static View offlineRow(Context c,Anime a,double episode,long bytes,Runnable open,Runnable delete){LinearLayout row=row(c);row.setPadding(dp(c,14),dp(c,11),dp(c,14),dp(c,11));row.setBackground(stroke(CARD,16,c));press(row);row.setOnClickListener(v->{if(open!=null)open.run();});ImageView poster=new ImageView(c);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setBackground(shape(SURFACE,11,c));poster.setClipToOutline(true);YoruApp.app().images.load(poster,a);row.addView(poster,lp(c,48,68));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.leftMargin=dp(c,12);LinearLayout text=column(c);text.addView(text(c,YoruBrain.title(a),13,TEXT,true));space(text,4);text.addView(text(c,"Серия "+number(episode)+" · "+bytes(bytes),11,MUTED,false));row.addView(text,tp);Icon del=new Icon(c,"trash");del.color=0xffff8f9f;del.setPadding(dp(c,8),dp(c,8),dp(c,8),dp(c,8));press(del);del.setOnClickListener(v->{if(delete!=null)delete.run();});row.addView(del,lp(c,38,38));return row;}
    public static View heroRow(Context c,String title,String desc,String actionTitle,Runnable action){LinearLayout card=column(c);card.setPadding(dp(c,18),dp(c,18),dp(c,18),dp(c,16));card.setBackground(stroke(CARD,22,c));card.addView(text(c,title,19,TEXT,true));space(card,6);TextView d=text(c,desc,12,MUTED,false);d.setLineSpacing(dp(c,3),1);card.addView(d);space(card,14);card.addView(button(c,actionTitle,true,action));return card;}
    public static View cardMini(Context c,Anime a){LinearLayout col=column(c);col.setPadding(0,0,dp(c,10),0);Card card=new Card(c,165);card.bind(a);col.addView(card,lp(c,134,-2));return col;}
    public static View chipSelect(Context c,String title,boolean active,Runnable click){TextView chip=chip(c,title,active,click);LinearLayout.LayoutParams p=lp(c,-2,-2);p.rightMargin=dp(c,7);chip.setLayoutParams(p);return chip;}
    public static View sectionHeader(Context c,String title,String actionText,Runnable action){LinearLayout row=row(c);row.addView(text(c,title,19,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));if(actionText!=null&&!actionText.isEmpty()){TextView act=text(c,actionText,11,PURPLE,true);act.setPadding(dp(c,10),dp(c,6),dp(c,10),dp(c,6));act.setBackground(stroke(SURFACE,11,c));press(act);act.setOnClickListener(v->{if(action!=null)action.run();});row.addView(act);}return row;}
    public static View statItem(Context c,String value,String label){LinearLayout col=column(c);col.setGravity(Gravity.CENTER);col.addView(text(c,value,18,PURPLE,true));space(col,2);col.addView(text(c,label,11,MUTED,false));return col;}
    public static View filterChip(Context c,String text,boolean selected,Runnable click){return chip(c,text,selected,click);}
    public static View sourceItem(Context c,String title,String desc,boolean checked,Runnable click){LinearLayout row=row(c);row.setPadding(dp(c,16),dp(c,13),dp(c,16),dp(c,13));row.setBackground(stroke(CARD,16,c));press(row);row.setOnClickListener(v->{if(click!=null)click.run();});RadioButton r=new RadioButton(c);r.setChecked(checked);r.setClickable(false);if(Build.VERSION.SDK_INT>=21)r.setButtonTintList(android.content.res.ColorStateList.valueOf(PURPLE));row.addView(r);LinearLayout text=column(c);text.setPadding(dp(c,8),0,0,0);text.addView(text(c,title,13,TEXT,true));if(!desc.isEmpty()){space(text,2);text.addView(text(c,desc,11,MUTED,false));}row.addView(text,new LinearLayout.LayoutParams(0,-2,1));return row;}
    public static View simpleItem(Context c,String text,Runnable click){TextView row=text(c,text,13,TEXT,false);row.setPadding(dp(c,14),dp(c,12),dp(c,14),dp(c,12));row.setBackground(stroke(CARD,14,c));press(row);row.setOnClickListener(v->{if(click!=null)click.run();});return row;}
    public static View roundIcon(Context c,String icon,int bg,int color,Runnable click){Icon i=new Icon(c,icon);i.color=color;i.setBackground(shape(bg,20,c));i.setPadding(dp(c,10),dp(c,10),dp(c,10),dp(c,10));press(i);i.setOnClickListener(v->{if(click!=null)click.run();});return i;}
    public static View labelValue(Context c,String labelText,String valueText){LinearLayout row=row(c);row.addView(text(c,labelText,12,MUTED,false));row.addView(new View(c),new LinearLayout.LayoutParams(0,1,1));row.addView(text(c,valueText,12,TEXT,true));return row;}
    public static View expandableSection(Context c,String title,View child){LinearLayout col=column(c);col.setBackground(stroke(CARD,16,c));col.setPadding(dp(c,14),dp(c,12),dp(c,14),dp(c,12));LinearLayout head=row(c);head.addView(text(c,title,13,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));Icon arrow=new Icon(c,"forward");arrow.color=MUTED;head.addView(arrow,lp(c,20,20));col.addView(head);child.setVisibility(View.GONE);head.setOnClickListener(v->{boolean open=child.getVisibility()==View.VISIBLE;child.setVisibility(open?View.GONE:View.VISIBLE);arrow.setRotation(open?0:90);});col.addView(child);return col;}
    public static View badge(Context c,String text,int bg,int textColor){TextView b=text(c,text,10,textColor,true);b.setPadding(dp(c,8),dp(c,4),dp(c,8),dp(c,4));b.setBackground(shape(bg,8,c));return b;}
    public static View searchBar(Context c,String hint,EditText[] out,Runnable onSearch){LinearLayout row=row(c);row.setPadding(dp(c,12),dp(c,6),dp(c,12),dp(c,6));row.setBackground(stroke(SURFACE,16,c));Icon i=new Icon(c,"search");i.color=MUTED;row.addView(i,lp(c,20,20));EditText edit=new EditText(c);edit.setHint(hint);edit.setHintTextColor(MUTED);edit.setTextColor(TEXT);edit.setTextSize(13);edit.setBackground(null);edit.setPadding(dp(c,8),dp(c,6),dp(c,8),dp(c,6));edit.setSingleLine(true);edit.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);edit.setOnEditorActionListener((v,actionId,event)->{if(onSearch!=null)onSearch.run();return true;});if(out!=null&&out.length>0)out[0]=edit;row.addView(edit,new LinearLayout.LayoutParams(0,-2,1));return row;}
    public static View qualityChip(Context c,int quality,boolean active,Runnable click){return chip(c,quality>0?quality+"p":"Авто",active,click);}
    public static View episodeRow(Context c,double ep,String title,String dur,boolean watched,Runnable click){LinearLayout row=row(c);row.setPadding(dp(c,12),dp(c,10),dp(c,12),dp(c,10));row.setBackground(stroke(CARD,14,c));press(row);row.setOnClickListener(v->{if(click!=null)click.run();});row.addView(text(c,"Серия "+number(ep),12,watched?MUTED:PURPLE,true));if(title!=null&&!title.isEmpty()){space(row,8);row.addView(text(c,"· "+title,12,TEXT,false),new LinearLayout.LayoutParams(0,-2,1));}else row.addView(new View(c),new LinearLayout.LayoutParams(0,1,1));if(dur!=null&&!dur.isEmpty())row.addView(text(c,dur,11,MUTED,false));return row;}
    public static View headerTitle(Context c,String title,String sub){LinearLayout col=column(c);col.addView(text(c,title,22,TEXT,true));if(sub!=null&&!sub.isEmpty()){space(col,4);col.addView(text(c,sub,12,MUTED,false));}return col;}
    public static View listDivider(Context c){View d=new View(c);d.setBackgroundColor(LINE);return d;}
    public static View tagView(Context c,String t){TextView v=text(c,t,10,MUTED,false);v.setPadding(dp(c,7),dp(c,4),dp(c,7),dp(c,4));v.setBackground(shape(SURFACE,8,c));return v;}
    public static View bulletItem(Context c,String t){LinearLayout row=row(c);View dot=new View(c);dot.setBackground(shape(PURPLE,3,c));row.addView(dot,lp(c,6,6));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.leftMargin=dp(c,8);TextView label=text(c,t,12,MUTED,false);label.setSingleLine(true);label.setEllipsize(android.text.TextUtils.TruncateAt.END);row.addView(label,lp);return row;}
    public static final class Card extends LinearLayout {
        private final ImageView image;private final TextView title,meta,tag,voice;
        public Card(Context c,int imageHeight){
            super(c);setOrientation(VERTICAL);setPadding(dp(c,4),dp(c,4),dp(c,4),dp(c,10));
            FrameLayout frame=new FrameLayout(c);frame.setBackground(stroke(CARD,16,c));frame.setClipToOutline(true);
            image=new ImageView(c);image.setScaleType(ImageView.ScaleType.CENTER_CROP);frame.addView(image,new FrameLayout.LayoutParams(-1,-1));
            View fade=new View(c);fade.setBackground(gradient(0x000d0b12,0xee0d0b12,16,c));frame.addView(fade,new FrameLayout.LayoutParams(-1,-1));
            tag=text(c,"",10,0xff21152f,true);tag.setPadding(dp(c,8),dp(c,5),dp(c,8),dp(c,5));tag.setBackground(gradient(0xffe2ccff,PURPLE,9,c));
            FrameLayout.LayoutParams label=new FrameLayout.LayoutParams(-2,-2,Gravity.BOTTOM|Gravity.START);label.leftMargin=dp(c,8);label.bottomMargin=dp(c,8);frame.addView(tag,label);
            voice=text(c,"",10,TEXT,true);voice.setPadding(dp(c,7),dp(c,4),dp(c,7),dp(c,4));voice.setBackground(stroke(0xcc15111c,8,c));
            FrameLayout.LayoutParams vp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.END);vp.topMargin=dp(c,8);vp.rightMargin=dp(c,8);frame.addView(voice,vp);
            addView(frame,new LinearLayout.LayoutParams(-1,dp(c,imageHeight)));
            title=text(c,"",13,TEXT,true);title.setMaxLines(2);title.setEllipsize(android.text.TextUtils.TruncateAt.END);
            LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(c,39));p.topMargin=dp(c,9);addView(title,p);
            meta=text(c,"",11,MUTED,false);meta.setSingleLine();meta.setEllipsize(android.text.TextUtils.TruncateAt.END);addView(meta,new LinearLayout.LayoutParams(-1,-2));
            press(this);
        }
        public void bind(Anime a){
            title.setText(YoruBrain.title(a));meta.setText(a.cardMeta());String chip=YoruBrain.chip(a);tag.setText(chip);tag.setVisibility(chip.isEmpty()?View.GONE:View.VISIBLE);
            if(chip.startsWith("Продолжить")){
                tag.setBackground(gradient(0xffe2ccff,PURPLE,9,getContext()));press(tag);
                tag.setOnClickListener(v->{
                    JSONObject h=YoruApp.app().store.progress(a);
                    String mode=h.optString("playerMode","auto");
                    double ep=h.optDouble("episode",1);
                    long seekMs=h.optInt("time",0)*1000L;
                    String dub=h.optString("dubbing","");
                    if(dub.isEmpty())dub=YoruApp.app().store.voiceFor(a);
                    openPlayer(getContext(),a,mode,ep,seekMs,dub);
                });
            }else{
                tag.setBackground(stroke(0xcc15111c,9,getContext()));tag.setTextColor(TEXT);tag.setOnClickListener(null);tag.setClickable(false);
            }
            String score=a.score>0?String.format(Locale.US,"★ %.1f",a.score):"";voice.setText(score);voice.setVisibility(score.isEmpty()?View.GONE:View.VISIBLE);
            YoruApp.app().images.load(image,a);
            setOnClickListener(vv->openDetails(getContext(),a));title.setOnClickListener(vv->openDetails(getContext(),a));image.setOnClickListener(vv->openDetails(getContext(),a));
            setContentDescription(YoruBrain.title(a)+". "+a.cardMeta());
        }
    }
    public static final class Icon extends View {
        private final Paint p=new Paint(3);private String kind;public int color=MUTED;public boolean filled=false;
        public Icon(Context c,String type){super(c);kind=type;}
        public void setKind(String type){kind=type;invalidate();}
        @Override protected void onDraw(Canvas c){
            super.onDraw(c);c.save();float size=Math.min(getWidth(),getHeight())*.62f;c.translate((getWidth()-size)/2,(getHeight()-size)/2);c.scale(size/24,size/24);
            p.setColor(color);p.setStrokeWidth(2.0f);p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeJoin(Paint.Join.ROUND);Path x=new Path();
            switch(kind){
                case "download":c.drawLine(12,3,12,16,p);c.drawLine(7,11,12,16,p);c.drawLine(17,11,12,16,p);x.moveTo(4,17);x.lineTo(4,21);x.lineTo(20,21);x.lineTo(20,17);c.drawPath(x,p);break;
                case "calendar":c.drawRoundRect(4,5,20,21,2,2,p);c.drawLine(4,10,20,10,p);c.drawLine(8,3,8,7,p);c.drawLine(16,3,16,7,p);c.drawLine(8,14,8,14,p);c.drawLine(12,14,12,14,p);c.drawLine(16,14,16,14,p);c.drawLine(8,18,8,18,p);c.drawLine(12,18,12,18,p);c.drawLine(16,18,16,18,p);break;
                case "search":c.drawCircle(10,10,6.3f,p);c.drawLine(15,15,21,21,p);break;
                case "back":x.moveTo(14,5);x.lineTo(7,12);x.lineTo(14,19);c.drawPath(x,p);break;
                case "close":c.drawLine(6,6,18,18,p);c.drawLine(18,6,6,18,p);break;
                case "play":x.moveTo(8,4);x.lineTo(20,12);x.lineTo(8,20);x.close();c.drawPath(x,p);break;
                case "heart":x.moveTo(12,20);x.cubicTo(-3,10,4,0,12,6);x.cubicTo(20,0,27,10,12,20);c.drawPath(x,p);break;
                case "home":x.moveTo(3,11);x.lineTo(12,3);x.lineTo(21,11);x.moveTo(6,10);x.lineTo(6,21);x.lineTo(18,21);x.lineTo(18,10);c.drawPath(x,p);break;
                case "grid":for(int i=0;i<2;i++)for(int j=0;j<2;j++)c.drawRoundRect(3+i*11,3+j*11,10+i*11,10+j*11,1.5f,1.5f,p);break;
                case "sources":x.moveTo(12,3);x.lineTo(22,8);x.lineTo(12,13);x.lineTo(2,8);x.close();x.moveTo(2,13);x.lineTo(12,18);x.lineTo(22,13);x.moveTo(2,18);x.lineTo(12,23);x.lineTo(22,18);c.drawPath(x,p);break;
                case "history":c.drawArc(4,4,21,21,-150,300,false,p);c.drawLine(3,4,3,10,p);c.drawLine(3,10,9,10,p);c.drawLine(12,8,12,13,p);c.drawLine(12,13,16,15,p);break;
                case "settings":c.drawCircle(12,12,6.1f,p);c.drawCircle(12,12,1.9f,p);for(int i=0;i<8;i++){c.save();c.rotate(i*45,12,12);c.drawLine(12,3.1f,12,5.6f,p);c.restore();}break;
                case "filter":c.drawLine(3,5,21,5,p);c.drawLine(6,12,18,12,p);c.drawLine(9,19,15,19,p);break;
                case "expand":c.drawLine(3,9,3,3,p);c.drawLine(3,3,9,3,p);c.drawLine(15,3,21,3,p);c.drawLine(21,3,21,9,p);c.drawLine(21,15,21,21,p);c.drawLine(21,21,15,21,p);c.drawLine(9,21,3,21,p);c.drawLine(3,21,3,15,p);break;
                case "shrink":c.drawLine(9,3,9,9,p);c.drawLine(9,9,3,9,p);c.drawLine(15,3,15,9,p);c.drawLine(15,9,21,9,p);c.drawLine(15,21,15,15,p);c.drawLine(15,15,21,15,p);c.drawLine(9,21,9,15,p);c.drawLine(9,15,3,15,p);break;
                case "pause":c.drawLine(9,5,9,19,p);c.drawLine(15,5,15,19,p);break;
                case "trash":c.drawLine(6,7,18,7,p);c.drawLine(9,7,9,5,p);c.drawLine(15,7,15,5,p);c.drawRoundRect(8,9,16,21,1.5f,1.5f,p);c.drawLine(10,12,10,18,p);c.drawLine(14,12,14,18,p);break;
                case "retry":case "refresh":c.drawArc(5,5,19,19,35,285,false,p);x.moveTo(18,5);x.lineTo(20,11);x.lineTo(14,9);c.drawPath(x,p);break;
                case "pip":c.drawRoundRect(3,5,21,19,2,2,p);c.drawRoundRect(12,12,19,17,1.5f,1.5f,p);break;
                case "rewind":x.moveTo(11,6);x.lineTo(4,12);x.lineTo(11,18);x.close();c.drawPath(x,p);x.reset();x.moveTo(20,6);x.lineTo(13,12);x.lineTo(20,18);x.close();c.drawPath(x,p);break;
                case "forward":x.moveTo(4,6);x.lineTo(11,12);x.lineTo(4,18);x.close();c.drawPath(x,p);x.reset();x.moveTo(13,6);x.lineTo(20,12);x.lineTo(13,18);x.close();c.drawPath(x,p);break;
                case "prevEpisode":c.drawLine(6,5,6,19,p);x.moveTo(18,5);x.lineTo(8,12);x.lineTo(18,19);x.close();c.drawPath(x,p);break;
                case "nextEpisode":c.drawLine(18,5,18,19,p);x.moveTo(6,5);x.lineTo(16,12);x.lineTo(6,19);x.close();c.drawPath(x,p);break;
                case "fit":c.drawRoundRect(4,6,20,18,2,2,p);c.drawLine(8,10,8,14,p);c.drawLine(16,10,16,14,p);break;
                case "smartfill":c.drawRoundRect(3.5f,5,20.5f,19,3,3,p);x.moveTo(8,9);x.lineTo(5.5f,9);x.lineTo(5.5f,6.5f);x.moveTo(16,9);x.lineTo(18.5f,9);x.lineTo(18.5f,6.5f);x.moveTo(8,15);x.lineTo(5.5f,15);x.lineTo(5.5f,17.5f);x.moveTo(16,15);x.lineTo(18.5f,15);x.lineTo(18.5f,17.5f);c.drawPath(x,p);break;
                case "telegram":x.moveTo(21,4);x.lineTo(3.4f,11.3f);x.lineTo(9.4f,13.7f);x.lineTo(11.9f,19.9f);x.lineTo(14.6f,15.1f);x.lineTo(20.4f,16.7f);x.close();c.drawPath(x,p);x.reset();x.moveTo(9.4f,13.7f);x.lineTo(16.2f,8.2f);c.drawPath(x,p);break;
                case "bell":x.moveTo(18,10);x.cubicTo(18,5.2f,15.3f,2.7f,12,2.7f);x.cubicTo(8.7f,2.7f,6,5.2f,6,10);x.lineTo(6,14);x.lineTo(4.6f,16.6f);x.lineTo(19.4f,16.6f);x.lineTo(18,14);x.close();if(filled){p.setStyle(Paint.Style.FILL);c.drawPath(x,p);p.setStyle(Paint.Style.STROKE);}else c.drawPath(x,p);x.reset();x.moveTo(10,19.4f);x.cubicTo(10.5f,20.7f,13.5f,20.7f,14,19.4f);c.drawPath(x,p);break;
                case "tiktok":x.moveTo(15,4);x.lineTo(15,14);x.moveTo(15,4);x.cubicTo(17,7,19,8,21,8);c.drawPath(x,p);c.drawCircle(11,15,3.8f,p);break;
                case "share":c.drawCircle(18,5,2.5f,p);c.drawCircle(6,12,2.5f,p);c.drawCircle(18,19,2.5f,p);c.drawLine(8.2f,10.9f,15.8f,6.1f,p);c.drawLine(8.2f,13.1f,15.8f,17.9f,p);break;
                case "volume":x.moveTo(5,9);x.lineTo(9,9);x.lineTo(14,5);x.lineTo(14,19);x.lineTo(9,15);x.lineTo(5,15);x.close();c.drawPath(x,p);c.drawArc(12,8,20,16,-60,120,false,p);break;
                case "mute":x.moveTo(5,9);x.lineTo(9,9);x.lineTo(14,5);x.lineTo(14,19);x.lineTo(9,15);x.lineTo(5,15);x.close();c.drawPath(x,p);c.drawLine(17,9,21,15,p);c.drawLine(21,9,17,15,p);break;
                case "bookmark":x.moveTo(6,4);x.lineTo(18,4);x.lineTo(18,20);x.lineTo(12,15);x.lineTo(6,20);x.close();c.drawPath(x,p);break;
                case "autoswipe":c.drawArc(4,4,20,20,-50,280,false,p);x.moveTo(17,3);x.lineTo(21,6);x.lineTo(17,9);c.drawPath(x,p);x.reset();x.moveTo(10.5f,9);x.lineTo(15.5f,12);x.lineTo(10.5f,15);x.close();p.setStyle(Paint.Style.FILL);c.drawPath(x,p);p.setStyle(Paint.Style.STROKE);break;
                case "mic":c.drawRoundRect(9,3,15,13,3,3,p);c.drawArc(6,6,18,15,0,180,false,p);c.drawLine(12,15,12,20,p);c.drawLine(8,20,16,20,p);break;
                default:c.drawCircle(12,12,8,p);c.drawLine(12,8,12,13,p);c.drawPoint(12,17,p);
            }
            c.restore();
        }
    }
    public static void openOffline(Context c,String id,Anime a,double episode){c.startActivity(new Intent(c,PlayerActivity.class).putExtra("anime",a.json().toString()).putExtra("downloadId",id).putExtra("episode",episode));}
    public static String bytes(long n){if(n<0)return "—";if(n>=1024L*1024*1024)return String.format(new java.util.Locale("ru"),"%.2f ГБ",n/(1024.0*1024*1024));if(n>=1024L*1024)return String.format(new java.util.Locale("ru"),"%.1f МБ",n/(1024.0*1024));if(n>=1024)return String.format(new java.util.Locale("ru"),"%.0f КБ",n/1024.0);return n+" Б";}
    public static String videoSizeHint(int quality,int seconds){int q=quality<=0?720:quality;int duration=seconds>90?seconds:24*60;double mbPerMin=q<=360?3.2:q<=480?5.0:q<=720?8.5:q<=1080?15.0:q<=1440?25.0:38.0;long low=Math.max(20,Math.round(duration/60.0*mbPerMin*.75));long high=Math.max(low+10,Math.round(duration/60.0*mbPerMin*1.35));return "примерно "+bytes(low*1024L*1024L)+"–"+bytes(high*1024L*1024L);}
}
